### ISSUE TITLE
Entering/exiting spectator mode during hero death causes permanent slow motion

### ISSUE THREAD

**Issue by NightKev** [HearthSim/hs-bugs#10]
If you enter or exit spectator mode while a hero's portrait is exploding in slow motion (in a match), the game remains in slow motion until the game client is restarted.
- http://us.battle.net/hearthstone/en/forum/topic/10388659372
- https://www.reddit.com/r/hearthstone/comments/35ldh8/slowmo_hearthstone/

**Comment by culinko** [comment]
I haven't been able to reproduce this in 4.1 yet. This is hard to test properly because of the exact timing, so it can still be bugged. However, I have found that if you click on your friendlist and prepare the "leave" button before the match is over and press it right after the Victory/Defeat screen is fading away, the blurry board image will still remain displayed. If you click on chat, menu or friendlist, they will remain displayed as well. You have to restart the client in order to continue.
* http://imgur.com/a/9pgpG

**Comment by troggnostupidhs** [comment]
I don't think this has been seen for a long time. Last reports on Reddit seem to be from almost a year ago. I believe this should be closed.

**Comment by troggnostupidhs** [comment]
Not updating the milestone since it isn't known when this was fixed.

**Comment by culinko** [comment]
You should still update the milestone to the current one.
