### ISSUE TITLE
When Gral, the Shark eats a minion with deck buff, he only gets initial stats

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#1100]
(3:30 to 4:30) https://www.bilibili.com/video/av42491057

3 Meat Wagons are shuffled to deck and then buffed to 2 attack by Keleseth. But when you play Gral, the Shark, he only shows a 1/4 Meat Wagon and gets +1/+4.

**Comment by PattuX** [comment]
So I assume this is Gral only considering the base stats and there's nothing special about Keleseth here?

Vague guess is that moving the entity to setaside (or graveyard? no idea what Gral actually does) causes enchanments to detatch. If so, what happens when doing the same setup with Immortal Prelate instead? And on that note: Does Gral then return a copy or the original entity? If the latter is the case there might be some weird stuff with Immortal Prelate as well.

**Comment by Jetz72** [comment]
Acknowledged as known issue:
https://us.battle.net/forums/en/hearthstone/topic/20763956467#post-9
>Gral, the Shark will only gain the base stats of a minion.

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/22911364

> Gral, the Shark will now correctly gain the extra stats if the minion it eats was buffed in the deck.
