### ISSUE TITLE
Misdirection will not activate if the only other target is a Stealthed Minion, even though Stealthed Minions are valid targets

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#121]
If you attack into Misdirection and the only other target is a Stealthed minion, then it will not trigger.

https://www.youtube.com/watch?v=m145byeiAgw

However, it is possible for Misdirection to select a Stealthed minion. The bug is that it does not trigger when it could have an effect.

**Comment by culinko** [comment]
This appears to be fixed in 3.1. Me and SimFri tested attacking with hero into misdirection while the only minion on the board was shade of naxx. I got misdirected into the shade (what needs to be checked is if the shade remained in stealth, it shouldn't, but I can't really remember if it did).

The minion attack was tested here: https://www.youtube.com/watch?v=C3nkR5w6AYU.
