### ISSUE TITLE
Jousted cards reveal their entity ID

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/hs-bugs#132]
When playing a joust, the jousted cards have their entity IDs revealed and can therefore be tracked when they move to the hand.

**Comment by jleclanche** [comment]
Hotfixed today. Jousts now create separate cards for the joust.

http://www.hearthpwn.com/news/1026-nozdormu-jousting-bug-has-been-hotfixed

**Comment by culinko** [comment]
Looks like there is still "tag=CREATOR value=xx" in the log. The value represents the minion's ID. I tested it only with my minions, but since you can see the opponent's creator value too, I assume you can still see their minion's real ID. This needs to be tested, so we can confirm or deny that you can see when your opponent draws the revealed card from joust.

**Comment by jleclanche** [comment]
Confirmed the new info leak. Nice fix. :p

**Comment by NightKev** [comment]
Blizzard please...

**Comment by Mischanix** [comment]
Log:

- [CREATOR tag revealed for Emperor Thaurissan](https://gist.github.com/Mischanix/1eebdc7a17dd6c6ec4d3#file-150904-joust-creator-log-L5152)
- [Thaurissan drawn](https://gist.github.com/Mischanix/1eebdc7a17dd6c6ec4d3#file-150904-joust-creator-log-L5728-L5730)

**Comment by jleclanche** [comment]
Another hotfix was pushed, removing the CREATOR tag. Confirming fixed.
