### ISSUE TITLE
Buff from Chromatic Dragonkin (Chromaggus) is Brow Furrow, from Floating Watcher

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/hs-bugs#135]
Chromatic Dragonkin doesn't have his own buff. He reuses Brow Furrow (`GVG_100e`).

![](https://cloud.githubusercontent.com/assets/235410/9709751/9b46ae5c-5531-11e5-857e-1ad6da48b9d3.png)

**Comment by Patashu** [comment]
#hearthsim. We discover only the FINEST premium bugs

**Comment by Patashu** [comment]
Probably fixed in 4.2

<jleclanche> !card BRMA12_8te
<CardBot> (1/1) Draconic Lineage [BRMA12_8te][BRM][Neutral Enchantment]: +2/+2
<jleclanche> !card BRMA12_8t
<CardBot> Chromatic Dragonkin [BRMA12_8t][BRM][Neutral Minion][2 mana, 2/3]: Whenever your opponent casts a spell, gain +2/+2. (Dragon)
<jleclanche> haha they fixed that

**Comment by jleclanche** [comment]
Fixed in 4.2.0.12051.
