### ISSUE TITLE
Poultryizer triggers Starving Buzzard

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#145]
When Poultryizer transforms a minion into a Chicken, Starving Buzzard will trigger.

Normally transformation effects that are related to a spell, such as Hex and Polymorph, do not participate in the Summoning Catchup Step and thus do not trigger Starving Buzzard, Commanding Shout, etc. Transformation effects that are related to a Battlecry, such as Faceless Manipulator and Recombobulator, do participate in the Summoning Catchup Step and thus do trigger Starving Buzzard, Commanding Shout, etc. Poultryizer fits into the latter camp, even though it feels like it should fit into the former camp.

https://www.youtube.com/watch?v=Gj3VUtx5c0s

**Comment by culinko** [comment]
Isn't Poultryizer considered a minion transformer and therefore should be in the respective group, rather than with other spell transformers?

**Comment by Patashu** [comment]
Some people, like jleclanche, argue that Recombobulator/Tinkmaster Overspark triggering Starving Buzzard is a bug. If you're in that camp, Poultryizer triggering Starving Buzzard is a bug.

Some people, like me, argue that Battlecry-related transforms trigger Starving Buzzard because they need to trigger SRS in general (for example, so Druid of the Claw vs Starving Buzzard has the intended result). If you're in this camp, Poultryizer triggering Starving Buzzard is a bug.

The problem is that since Commanding Shout is an SRS trigger, but worded like it's an aura (or MTG style static effect), no matter which camp you fall in Commanding Shout will erroneously not protect some group of transformed minions.

**Comment by Patashu** [comment]
Lady Naz'jar ("An Evil Exchange") also triggers Starving Buzzard.

https://www.reddit.com/r/hearthstone/comments/4bpgu6/interaction_between_starving_buzzard_and_lady/

**Comment by PattuX** [comment]
Probably fixed, as the special SRS seems to be missing in 5.0

* https://youtu.be/iqiIjdrUAXo

No info on whether it is intended yet, so it might be reverted in an upcoming patch.

**Comment by Patashu** [comment]
https://twitter.com/ywoo_dev/status/798021913545056258

Ywoo is looking into the inconsistency between Master of Evolution and Evolve (where the former respects the Miniature Warfare tavern brawl rule and the latter does not). Maybe it should be its own bug entry.

**Comment by Patashu** [comment]
Someone needs to test if Lotus Illusionist (which is a new timing for a transform effect, it wasn't possible to happen during combat before) triggers Unlicensed Apothecary (the new best SRS trigger, as it triggers no matter what) or not.

**Comment by PattuX** [comment]
https://youtu.be/YdWUhRjUIvQ?t=1m40s

Hero cards (specifically Thrall) trigger Buzzard, too. I don't know about the hero power.

**Comment by troggnostupidhs** [comment]
https://youtu.be/xxmD2r3FSCM?t=116

**Comment by troggnostupidhs** [comment]
Anyone want to test Poultryizer ?

https://playhearthstone.com/en-us/blog/21802981
>Transform effects such as Thrall, Deathseer will no longer activate summon triggers like Starving Buzzard and Blubber Baron.

**Comment by Kybxd** [comment]
The transforming mechanics and Summon Resolution mechanics are completely changed. Here are my results:

1. There is no more 'Summon Resolution Step'. As for summoned minions, the process is like this:
The minion enters board - On Summon - After Summon

For example if you have a Buzzard/KJ with 7 Ancestral Spirits, Buzzard draws 6*7=42 but KJ shoots 1+2+3+4+5+6=21 before Patch 11.2. But after update they both draw/shoot 21.
In animations they are also same: Buzzard1, Buzzard2, 1 draws , Buzzard3, 1&2 draw , etc.
Another Example: You have SoJ and Steward of Darkshire, and use updated paladin hero power. SHR1 gains Divine Shield and then +1+1. Then SHR2 is summoned, it gains Shield and +1+1.

As for played minions, Play Sequence is like this:
On play - Overload - _On Summon_ / Targeting - Battlecry / _After-Summon_ - Echo - _After Play_
(Previous: On play - Overload / Targeting - Battlecry / After-Play - Echo - After Summon)

1) On Summon Triggers still work after On Play and before Battlecry for played minions. But I don't use the word 'Summon Resolution Step' anymore because its interactions with summoned minions are changed.
2) The order of After Summon/After Play is changed, I guess a possible reason is to avoid minions killed by Explosive Runes being saved by SoJ?

2. Only Choose-One transformations triggers On Summon & Jungle Giants. The order is:
Choose-One transformation - On Summon - After Summon - After Play

1) Whether Death Creation Step run in-between is untested yet.
2) The missing of Echo is a bug, I mentioned it in #970.

Other transformations doesn't trigger On Summon, including Faceless, Druid of the Fang, Recombobulator, etc.

**Comment by PattuX** [comment]
> There is no more 'Summon Resolution Step'.

Well, I guess at least something good game out of this.

> Choose-One transformation - On Summon - After Summon - After Play

Is On Play missing too or did you just forget to mention or didn't test?

**Comment by troggnostupidhs** [comment]
This is fixed?

**Comment by PattuX** [comment]
If Poultryizer now also uses CHANGE_ENTITY (like all other transform effects) it should be as there is no summoning action for the chicken anymore (since there is no new entity to be summoned). So it should be, but I don't have Gelbin to test.

**Comment by Kybxd** [comment]
> Is On Play missing too or did you just forget to mention or didn't test?
I thought it was similar to normal minions, but after a complete test it's different. See #970.
Besides there is a mistake above: On Summon is before Overload in Play Sequence.
