### ISSUE TITLE
Steal effects in-hand ignore hand size limit

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#174]
If you cast Mind Control on a minion, but before the Spell Text Phase, the minion is returned to the opponent's hand AND your hand contains 10/10 cards, the spell will resolve by moving the minion into your hand without first checking for it being full, leading to you having 11 cards in your hand simultaneously.
- https://www.youtube.com/watch?v=8GbKPLvUHZk

**Comment by Patashu** [comment]
Reproduced in 4.0

https://youtu.be/-vwyJCVx2Gc

**Comment by Patashu** [comment]
Confirmed in 4.1

https://www.youtube.com/watch?v=kSVz3pIhjVw

**Comment by culinko** [comment]
We tested today that the steal effects in-deck also ignore the deck limit: https://www.youtube.com/watch?v=7nuxCrffW2k.

**Comment by culinko** [comment]
You can't bypass the hand limit of 10 cards with steal effects in-hand anymore. We tested Mind Control and Shadow Madness and the stolen card goes to graveyard (accompanied by the "discard" visual effect). There is no way to test the deck limit anymore since Malorne's and Weasel Tunneler's behavior have been recently changed.
