### ISSUE TITLE
Hidden quest buffer allows you to store up to 6 quests simultaneously

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#266]
If you don't complete your quests for 6 days and don't use the reroll function on them, you can store up to 3 quests in the hidden buffer, making it 6 quests in total.
* https://www.reddit.com/r/hearthstone/comments/3t9wx3/2_tips_that_i_never_see_anyone_mention_that_are/cx4ma95?context=100

This has been confirmed as a bug by Ben Brode:
* https://twitter.com/bdbrode/status/667049642484363264

**Comment by mthuurne** [comment]
On 2016-01-29, I won a travern brawl and got shown progress (Druid+Hunter 1/5 wins) on a quest that wasn't in my list of 3 visible quests. I hadn't played on the days before, so there would have been quests in the hidden quest buffer.

On 2016-01-30, I played until my 3-quest list was empty.

On 2016-02-01, I got 3 new quests, one of which was 5 wins with Druid and/or Hunter. However, the progress counter was at 0/5.
At least one of those 3 quests must have come from the hidden quests buffer, otherwise I would have had only 2 quests because only 2 midnights had passed since my quest list empty.

My guess is that quests in the hidden quests buffer can progress, but the progress is reset when the quest is moved from the hidden buffer to the visible quests list.

What is strange though is that I haven't heard anyone else report this yet. Maybe it happens only on tavern brawls and not on ladder play? Or maybe it's related to the bug where normal quest progress is not displayed after a match, but is visible when you log in again?

**Comment by culinko** [comment]
Reported in 4.2: https://www.reddit.com/r/hearthstone/comments/4cx7w1/3_quests_for_today/.

However, there have been other reports saying it doesn't work, so I'm not bumping the milestone yet until I get more confirmations of this bug.

**Comment by riQQ** [comment]
Works for me in 4.2.

**Comment by riQQ** [comment]
Still works in 5.0.

**Comment by riQQ** [comment]
Works in 5.0.0.13030.

**Comment by riQQ** [comment]
Works in 5.2.0.13740.

**Comment by Patashu** [comment]
According to http://us.battle.net/forums/en/hearthstone/topic/20749867298 this is FINALLY fixed. Wow...

**Comment by riQQ** [comment]
Can confirm, this is fixed.
