### ISSUE TITLE
Daily quest not received

### ISSUE THREAD

**Issue by culinko** [HearthSim/hs-bugs#278]
Sometimes you don't receive a daily quest after logging in. You will have to finish a game or restart the client one more time in order to receive it. This has started happening a couple of patches ago.
- https://www.reddit.com/r/hearthstone/comments/3vlbmo/daily_quests_not_triggering/

**Comment by jleclanche** [comment]
@culinko I just created a quests label, easier now.

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20759438615

There's a current problem where daily quests aren't being given each day.

One post describes a more elaborate process, compared to restarting the client, to getting the quest 

>1. Log in to Battle.net on my main account.
>2. Start Hearthstone. Daily quest does not appear. Exit Hearthstone.
>3. Log out of Battle.net
>4. Log in to Battle.net on a separate account
>5. Start Hearthstone. Quests on this account appears. Exit Hearthstone.
>6. Log out of separate account.
>7. Log back in to main account.
>8. Start Hearthstone. Now the daily quest appears.

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/7j0v3g/has_anyone_that_has_stopped_getting_quests_got/ 

Relogging  multiple times is another solution.  That somewhat works for me.

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/7j423y/if_you_dont_receive_daily_quest_change_the/

https://www.reddit.com/r/hearthstone/comments/7jz147/i_have_to_change_language_every_day_just_to_get/

Changing the language is the most effective for me.

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/7kgzqw/daily_quest_bug_megathread/

**Comment by troggnostupidhs** [comment]
That issue was resolved. I don't know if the original issue was also fixed.

https://us.battle.net/forums/en/hearthstone/topic/20760816674

Greetings,

Thanks for helping to make the launch of Kobolds & Catacombs legendary! Millions of players joined us to explore the vast kobold dungeons, and we hope all your adventures into the depths have been incredibly fun. 

After launch, we discovered something not-so-fun: an issue that delayed some players from receiving new daily quests after logging in, largely due to the unexpected impact that so many Dungeon Runs had on our services. We immediately set to work investigating the issue and implemented hotfixes to resolve it. We’re still working on it, but at this point the delay is significantly reduced, and in most cases players will now see their daily quests immediately upon log in.

Due to the nature of the issue, some players may still experience a delay between 10-30 minute after logging in to get their daily quest. Here are some steps you can take to prompt the quest log to update if you are not already seeing new quests upon login.

•	Check your quest log 10-30 minutes after logging in for the first time after quests reset. You need not remain logged in for that time.

•	Manually refresh the quest log by pushing the Quest Log button.

•	Play games in Play Mode or Arena (Note that Dungeon Run will not cause the quest log to update). 

•	Note: If you happen to complete your quest without seeing the quest log update, you’ll still be properly rewarded.

> 
> 
> We’re currently working on short-term solutions that should soon make these additional steps unnecessary, and we plan on implementing better long-term solutions in the new year. 
> 
> We understand how important daily quests are to the experience of Hearthstone, and we’re sorry for any confusion or frustration affected players might have experienced. As a celebration of Kobolds and Catacombs and a thank you to affected players for being patient while we worked to fix this issue, we’re sending all Blizzard players three Kobolds & Catacombs card packs, for free, on us!
> 
> Your free card packs will arrive via Blizzard Battle.net gifting in early January. To redeem on mobile, just log into Blizzard Battle.net via your favorite browser. If you’re on PC, you can click the gift icon on the upper right next to your Battletag. If your packs don’t appear in-game after you claim them, please try restarting Hearthstone.
> 
> Thanks for joining us in the tavern, and we wish you warmth and joy for the holidays!

**Comment by troggnostupidhs** [comment]
https://us.battle.net/forums/en/hearthstone/topic/20769477004?page=2#post-30

Reports of no quests

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/cnq0zi/no_daily_quests/
https://www.reddit.com/r/hearthstone/comments/cnl6ah/no_quest_bug/
https://www.reddit.com/r/hearthstone/comments/cnmlcy/bug_have_not_received_a_daily_quest_for_the_last/
https://www.reddit.com/r/hearthstone/comments/cnk3f9/no_quest_today/

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/cnk3f9/no_quest_today/ewcoaqa/

> 
> Greetings, all.
> 
> This is an issue we're currently investigating. I will update you in this thread as soon as I've more details.
> 
> Appreciate your patience!
>

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/cnk3f9/no_quest_today/ewcoaqa/

> Greetings, all.
> 
> This is an issue we're currently investigating. I will update you in this thread as soon as I've more details. Appreciate your patience!
> 
> **_Update 8/11:_** We're continuing to investigate this issue, but as of yet do not have an ETA as to when a fix will be implemented. I'll keep updating this post as I get more information!
> 
> **_Update 8/12:_** A hotfix has been implemented to resolve this issue. Please let me know if you experience the issue again.
>
