### ISSUE TITLE
Fandral Staghelm + Raven Idol may offer you the same choice multiple times

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#482]
- http://us.battle.net/hearthstone/en/forum/topic/20743594524

**Comment by culinko** [comment]
Not exclusive to spells.
https://www.reddit.com/r/hearthstone/comments/4gymt8/fandral_staghelmraven_idol_discover_bug/

**Comment by SimFriHS** [comment]
Fandral Staghelm + Raven Idol offering three Moonfires on the HearthstoneFR stream https://www.twitch.tv/hearthstonefr/v/65299063?t=01h36m54s

**Comment by VoidMayonnaise** [comment]
I tested for about 30 times and none of them discovered two or three same spells.
Druid has 39 spells(maybe more), If it really can discover same spells, the chance is (39C2+39C1)/39C3=8.5%, so I still need more data to draw the conclusion, maybe 100 or more times will be convincing.

**Comment by troggnostupidhs** [comment]
This one will be hard to prove.

**Comment by VoidMayonnaise** [comment]
Tested for another 115 times, 60 for Druid and 55 for Mage, all of them interacts correctly. The test is long and boring, so I didn't make the video. The information is recorded by Hearthstone Box.
(Using Violet Illutionist to immune to fatigue damage and using Astral Communication to discard useless cards)
Druid has 39 spells and Mage has 42 spells, if Ravel Idol can really discover the same spell, the chance that so many tests didn't happen is [1-(39*38*3+39)/39^3]^60*[1-(42*41*3+42)/42^3]^55=0.016%, a very small chance, so we can confirm the interaction has fixed, since it won't be meaningful if we continue testing.
It's a devil‘s proof...

**Comment by troggnostupidhs** [comment]
Personally, I feel that it also hasn't been reported for a long time

**Comment by VoidMayonnaise** [comment]
The chance is low enough, so I suggest that we should close this issue until someone find out it works again. We should avoid doing devil's proof.
