### ISSUE TITLE
Y'Shaarj + N'Zoth have each others' SFX

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#494]
Analysis here: https://www.reddit.com/r/hearthstone/comments/4hcmrs/bug_yshaarj_and_nzoth_are_using_the_wrong_voice/

**Comment by troggnostupidhs** [comment]
Comments on that post give various reasons why it could be intended. Also pointed out, Hearthstone uses different character art on several cards. Since they haven't changed it, I think it is intended.

> Y'Shaarj does in fact say both things in WoW.
N'zoth does not yet exist in WoW, so it is likely that the developers actually used prior samples of Y'Shaarj's whispers for N'zoth as well.

> Not really , All of the lines that you hear from N'zoth are things that Y'shaarj said in WoW they just gave it to N'zoth for no reason. Besides the "Gorge your hatred, embrace your rage" are one of the key quotes he whispers you in-game as he is the source of the Sha (things that feast on negative emotions) Sha of hatred and Sha of Anger are both part of it.
