### ISSUE TITLE
If you have Spell Damage +1, Forbidden Flame does not get the animated effect

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#537]
e.g. no sparkles
- https://www.reddit.com/r/hearthstone/comments/4k6j2a/forbidden_flame_should_sparkle_when_you_mouse/

**Comment by Patashu** [comment]
Also need to check:

Do Lightbomb/Shield Slam/Savagery/Blade Flurry/Shadowflame sparkle?

Does Betrayal NOT sparkle?

What about healing converted to damage (circle, forbidden healing, etc)? I can see this one going either way.

**Comment by culinko** [comment]
Tested everything just now:

The healing cards don't sparkle if they have been converted to damage with spell damage on board, also the values on the card don't change (e.g. Circle always shows 4 - which is logical since healing can't get boosted by spell damage and the card text doesn't change to damage instead of healing).

Lightbomb, Shield Slam, Savagery, Blade Flurry and Shadowflame do sparkle.
Betrayal does no sparkle.

**Comment by Patashu** [comment]
Thanks! So Forbidden Flame is the only one that's incorrect.

**Comment by jleclanche** [comment]
It's the `AFFECTED_BY_SPELL_POWER` tag, visible in carddefs.

**Comment by troggnostupidhs** [comment]
![hearthstone screenshot 12-18-16 14 30 20](https://cloud.githubusercontent.com/assets/22508641/21295992/c7ed63ec-c52e-11e6-9301-01b36fff1ee0.png)

**Comment by troggnostupidhs** [comment]
Forbidden Flame has the correct animation. Any spell that has a number does not have the animation, but the number updates correctly. I'm not sure if that is intended.
