### ISSUE TITLE
The priority of Animated Armor seems to be the highest among Predamage Triggers now

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#557]
I've retested the Predamage Triggers section of Rulebook with my friend,and found 2 examples of Rulebook are incorrect now.Here are my videos:

Animated Armor is prior to Ice Block,despite being later played (https://youtu.be/mSS1fI32J60)
Animated Armor is prior to Bolf,despite being later played (https://youtu.be/yhrw56me9Zo)

So I think the priority order is as follows:
1.Animated Armor has the highest priority.
2.Cursed Blade has the secondary priority.
3.Bolf/Ice Block have the lowest priority.The trigger order of them is decided by the play order.

**Comment by Patashu** [comment]
Interesting. I think this is intended, so I put the may-be-intended label on it. This should be integrated into the wiki and advanced rulebook asap.

(Also, for the record - I don't believe Cursed Blade is a trigger, it's just a continuus effect. A good example of this is if you have multiple Animated Armors and Cursed Blade, each Animated Armor triggers because Cursed Blade is keeping the incoming damage at 2, not 1.)

**Comment by Patashu** [comment]
I'll close this since jleclanche closed the ice barrier issue. This is very likely to be intended.

Keep reporting mechanics changes to me though! I'll continue updating the wiki with your findings.
