### ISSUE TITLE
Elusive effect on newly played/summoned minions does not update until an outermost Phase resolves

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#578]
Because of this, in the Servant of Yogg-Saron Tryouts Tavern Brawl, a played Elusive minion (such as Soggoth the Slitherer) can target itself with its spell.

(This currently only matters in that specific Tavern Brawl, but indicates a bug with the mechanic itself.)

Similar properties like Divine Shield instantly take affect when the minion is summoned or enters play. 

![image](https://cloud.githubusercontent.com/assets/666597/16826960/40097c84-49c5-11e6-96e5-483ad30cb6bc.png)
- https://www.reddit.com/r/hearthstone/comments/4sqqta/tavern_brawl_cant_be_target_by_spells_and_hero/

**Comment by jleclanche** [comment]
It's not really a bug, it's just the tags aren't present in the base card, unlike divine shield. I think you'll find (if you can figure out a way for it to matter) that it's the same for spellpower and cant_attack.

I'd like to see this fixed if only so that I don't have to do [this nasty stuff](https://github.com/HearthSim/extract-scripts/blob/526c4aeb59bacc55e287b36c481f2ec6ef6a0c3f/process_cardxml.py#L359-L392) anymore.

**Comment by Patashu** [comment]
AFAIK Spell Damage +1 is applied if you play a SP+1 minion and it casts a damage spell. (Culinko or PattuX said it works)

**Comment by Patashu** [comment]
[irc] <zombie_> this brawl just casted savagery on spectral knight ​

[irc] <NightKev> that's not supposed to happen ​

[irc] <zombie_> right ​

[irc] <zombie_> i'm positive ​

= confirmed on latest patch

**Comment by troggnostupidhs** [comment]
After many attempts I was able to test this. I think it is fixed.

https://www.youtube.com/watch?v=VzfAQigRIWc
