### ISSUE TITLE
When Darkspeaker swaps stats, its 'DAMAGE' is not set to 0

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#591]
One of my friend told me that in the Servant of Yogg-Saron Tryouts brawl, he played Darkspeaker and targeted a 0/2 totem, then Darkspeaker was Lava Shocked (random spell) to 3/4. When its Battlecry resolved, totem was 3/4 but Darkspeaker was 0/0 (immediately destroyed).

Then he tested it with Illidan and found this bug did exist in play mode. (https://youtu.be/kv5GHkUpfLU)

**Comment by Patashu** [comment]
Thanks for testing. This brawl has been very good for finding bugs.

**Comment by culinko** [comment]
To collect all evidence here, this is a report from reddit from the time it was discovered: https://www.reddit.com/r/hearthstone/comments/4sqf1t/possibly_the_best_tavern_brawl_opener_ever/d5bueh3.

I also confirmed it with a friend today with the simple test. Darkspeaper swapping stats with Illidan and 1 Sheep exploding before the battlecry happens. Darkspeaker should have been a 7/3 instead of 7/1. Here is the log: https://gist.github.com/culinko/4c88c2591f3d0b3f769b2a1eff8ac91e.

![hearthstone screenshot 07-23-16 21 20 54](https://cloud.githubusercontent.com/assets/11700272/17080203/aab51328-5126-11e6-9f06-bc0429be6bd1.png)

**Comment by culinko** [comment]
Vol'jin does not have the same bug. Tested with Illidan and Tentacle of N'Zoth. Log: https://gist.github.com/culinko/88adbb3ba5aef56dbfa96eb06bc66328.

![hearthstone screenshot 07-26-16 02 23 46](https://cloud.githubusercontent.com/assets/11700272/17122043/75071650-52d8-11e6-815b-8f2087d1f660.png)

**Comment by VoidMayonnaise** [comment]
https://youtu.be/Q51_voet2bI
Already fixed.
