### ISSUE TITLE
Genzo, the Shark + Mayor Noggenflogger can cause two Genzo triggers

### ISSUE THREAD

**Issue by Patashu** [HearthSim/hs-bugs#681]
* https://www.reddit.com/r/hearthstone/comments/5ly71e/genzo_the_shark_and_mayor_noggenfogger_fatigue/

We know this is a bug because Cutpurse + Misdirection used to be able to trigger twice ( https://github.com/HearthSim/hs-bugs/issues/281 ), and it got fixed by moving Cutpurse from the Proposed Attack Event to the Attack Event (see http://hearthstone.gamepedia.com/Advanced_rulebook#Combat ).

**Comment by troggnostupidhs** [comment]
https://youtu.be/xxmD2r3FSCM?t=67

**Comment by Kybxd** [comment]
Genzo is now a trigger on the Attack Event like Cutpurse. It still triggers when it's mortally wounded (Explosive Trap). All of its conditions must be met at the start of Attack Sequence. (Your Genzo attacks when both players have 3 cards, but you discard one due to Explosive Trap + Howlfiend. Genzo doesn't trigger.)

**Comment by troggnostupidhs** [comment]
Fixed?
