### ISSUE TITLE
Sacred Trial would trigger even if minion mortally wounded/pending destroy

### ISSUE THREAD

**Issue by 10925** [HearthSim/hs-bugs#698]
Hi we know secret changes a lot in patch 7.1, my friend in our QQ group made a video test most interactions: 
https://www.youtube.com/watch?v=naRlE4DhRfY&feature=youtu.be

You can find a summary Engligh Table in gamepedia usertalk:
https://hearthstone.gamepedia.com/Talk:Advanced_rulebook#

While Sacred Trail would be the most weird one after changes.

**Comment by Patashu** [comment]
Wow, thanks for the comprehensive overview. A surprising number of undocumented changes in this patch. I will have to look through them later. (I'll edit the table to bold interactions that changed, so it's easier to read quickly.)

**Comment by Patashu** [comment]
Oh! 10925, I have a request for you. In the patch 7.1 changelog it was said that Snipe now triggers after Potion of Polymorph. Does this mean that Snipe now triggers before all after After Phase triggers (high priority), that Potion of Polymorph now triggers after all other After Phase triggers (low priority), or does it not mean that they changed any priorities, just that they fixed the interaction to work meaningfully?

**Comment by Patashu** [comment]
Ok, I found something that IS worth testing - now that Mirror Entity doesn't have its old bug of triggering on the played minion even if it has left play, but DOES still trigger on Lord Jaraxxus to create a copy of Lord Jaraxxus the Minion, does it display the same side-effects of the hard-coded interaction that the other three Secrets bear? They're listed here:

https://hearthstone.gamepedia.com/Advanced_rulebook#Lord_Jaraxxus_vs_Secrets

**Comment by Kybxd** [comment]
I tested the second side-effect with my friend and here are the results:
1.Mirror Entity still doesn't trigger.(https://youtu.be/nS9uui5_U-c)
2.Snipe and Repentance trigger.(https://youtu.be/2bXXvzrW1Zg)(https://youtu.be/6jvC7IU_gwA)
3.Sacred Trial doesn't trigger whichever side of the board has 3 or more minions.(https://youtu.be/yCNVQTA6wIg)(https://youtu.be/sYll3jRxiv8)

**Comment by Patashu** [comment]
Thanks for your investigations. It seems like even between Secrets the hard-coding is inconsistent :)

The next time you are doing science, if you need ideas to test, ctrl+f for TODO in the advanced rulebook. Some of these TODOs are about rewriting parts of the advanced rulebook to be cleaner, but a lot of them ask for a test to be done. I just added two TODOs to Lord Jaraxxus vs Secrets, as follows:

TODO: It is currently unknown if Sacred Trial, Repentance, Snipe or Potion of Polymorph does or does not trigger on your own played non-Jaraxxus minion (stolen before After Play Phase). Of the Secrets, only Mirror Entity has been tested.

TODO: It should be tested if Sacred Trial, Snipe or Mirror Entity has the same timing as Repentance when triggering on Lord Jaraxxus the Hero (first Weapon Update Step following the Battlecry Phase, rather than during the After Play Phase).

**Comment by Kybxd** [comment]
* https://youtu.be/646mObaNiBs

Repentance now does not work on mortally wounded minions.

**Comment by troggnostupidhs** [comment]
Does Sacred Trial also need to be tested?

**Comment by Kybxd** [comment]
Sacred Trial still works on mortally wounded or pending destroy minions.

**Comment by Kybxd** [comment]
Sacred Trial is also fixed now.

**Comment by troggnostupidhs** [comment]
With this patch or 9.0.0.20457?

**Comment by Kybxd** [comment]
I tested it yesterday before the update of 10.0. So this should be fixed in 9.4 or an earlier patch.
