### ISSUE TITLE
Holy Wrath doesn't deal any damage when the card is milled

### ISSUE THREAD

**Issue by Kybxd** [HearthSim/hs-bugs#733]
* https://youtu.be/dyHOPKrboSY

**Comment by Patashu** [comment]
Looks like this is a functional change, because

https://hearthstone.gamepedia.com/Holy_Wrath#Notes

lists

If your hand is full when Holy Wrath draws a card, this spell will still deal damage equivalent to the card's mana cost, despite overdrawing the card.[2]

[2] is

 Tested by WillyK in Patch_2.7.0.9166 (Tavern Brawl patch). Re-tested by \u\steamgears92 in Patch 3.0.0.9786 (TGT patch)

So no video, but confirmed by two people a long time ago.

**Comment by VoidMayonnaise** [comment]
https://youtu.be/fTM9wsKT3rE
Confirmed in 8.2.2.

**Comment by troggnostupidhs** [comment]
https://www.youtube.com/watch?v=jArfMxDLl0U

**Comment by 10925** [comment]
Seems like this bug has been fixed.

**Comment by troggnostupidhs** [comment]
![img001](https://user-images.githubusercontent.com/22508641/39903088-6e3c9686-549f-11e8-91cb-87ba72b114d7.png)
