### ISSUE TITLE
Renounce Darkness is able to choose Warlock as the replacement class

### ISSUE THREAD

**Issue by 10925** [HearthSim/hs-bugs#747]
report from nga:http://bbs.nga.cn/read.php?tid=11749448&_ff=422
video:http://v.youku.com/v_show/id_XMjgwMjQ2NjIwNA==.html?spm=a2h3j.8428770.3416059.1

The author first use Finley transform to Priest's hero power,then uses Renounce Darkness back to warlock's, and replace warlock cards to new warlock cards that get (1) less mana.

I guess the new way how Renounce Darkness code is to first transform your hero power that different from current hero power's class, then replace your warlock class cards to that class.

It should to be see as a bug since the text says,"Replace... your warlock cards with another class's" which indiciate you should got non-warlock class cards.

**Comment by NightKev** [comment]
Well I'm unable to watch the video and I couldn't reproduce the bug in the current patch (9.0.0.20457).

**Comment by troggnostupidhs** [comment]
I was able to reproduce it.

![hearthstone screenshot 08-14-17 21 47 30](https://user-images.githubusercontent.com/22508641/29299192-f119fef6-813a-11e7-997f-af97c80b4b6f.png)

**Comment by troggnostupidhs** [comment]
Some calculations I did. I believe with 20 tries, it should be reproduced 90% of the time. And 39 times gives 99%.

"Replace your Hero Power and Warlock cards with another class's. The cards cost (1) less."

The next question is, is it a bug? By the wording, I think so. However, there have been other cases where the wording doesn't exactly match the behavior. I'm not sure if there is an argument that this is fine because it is accurate the majority of the the time.

The wiki is incorrect. Based on this issue, Renounce works differently that the way it describes.
https://hearthstone.gamepedia.com/Renounce_Darkness#Notes
> Renounce Darkness is coded in the following way:
First, select a random non-warlock class (which can happen to be even the same as the class of your current hero or Hero Power).

**Comment by troggnostupidhs** [comment]
I think the issue is that 'class' seems to be determined by the Hero Power in this case, instead of the current Hero class.

Deck
AAEBAfqUAwTtBZAHrRCEFw37AZwC8gW5BsQIzAi9rALTxQLnywLx0ALy0AKI0gKm8AIA

**Comment by troggnostupidhs** [comment]
I think the issue is that 'class' seems to be determined by the Hero Power in this case, instead of the current Hero class.

I tried 20 times and was not able to get Warlock, but more testing is needed.

Deck
AAEBAfqUAwTtBZAHrRCEFw37AZwC8gW5BsQIzAi9rALTxQLnywLx0ALy0AKI0gKm8AIA

**Comment by ceceita** [comment]
0/14
0/30 with Archmange Vargoth interaction

im pretty sure from 2017 there was alot of sir finley , renounce darkness fixes .
This bug was also previous to the release of TFT that added new dk heropowers

https://github.com/HearthSim/hs-bugs/issues/898

i think we can close alot of old bug reports and maybe reopen if they come back.

**Comment by troggnostupidhs** [comment]
I think it is likely fixed. If anyone has proof of this happening, we can reopen this issue.
