### ISSUE TITLE
Defile uses Forced Death Phase mechanics which makes unusual interaction

### ISSUE THREAD

**Issue by 10925** [HearthSim/hs-bugs#784]
![4aca284f78f0f73662526ceb0055b319e9c413de](https://user-images.githubusercontent.com/15797857/29247663-4957364c-803c-11e7-9763-83fe0bcdb636.jpg)

So, after the first Defile cast, Hyena would stay at 1 health, and the second Defile would assume it kills 1 health Hyena, but then the Hyena get the buff, and became a 6/1, then the 3rd defile really kill Hyena this time, and cast the 4th time.

Here are some similar tests I do:
https://drive.google.com/open?id=0B2RvTv3FXN-pMERKNVFEZEttdWM
https://drive.google.com/open?id=0B2RvTv3FXN-pMDBvZGtkRXllTTg
https://drive.google.com/open?id=0B2RvTv3FXN-pdnRrd0hVcXlNYVU

**Comment by 10925** [comment]
Report from reddit:
https://www.reddit.com/r/hearthstone/comments/6tcmfn/bugged_interaction_between_defile_and_scavenging/

**Comment by Patashu** [comment]
Is it tested that Defile works the same as other Forced Death Phase mechanics?

**Comment by troggnostupidhs** [comment]
Is this similar to Mortal Coil + Daring Reporter?

**Comment by Kybxd** [comment]
https://youtu.be/grsOn8HUuiw

**Comment by Kybxd** [comment]
This is fixed now.
You have a 2-health Scavenging Hyena, two 1/1 beast and cast Defile. Defile only deals AoE damage twice now.
In the example of Steward of Darkshire, Protector is now given Divine Shield immediately it's resummoned  by Redemption. (It's useless because she already has it.)

To make sure whether Forced Death Phase is completely changed, I also tested this:
I have an Explosive Sheep and a Haunted Creeper and cast Defile. Defile kills Sheep and damages Haunted to 1 health. Sheep's Deathrattle damages Haunted to -1 health. Defile damages Haunted to -2 health. Haunted dies and summons 2 Spiders. **Defile stops and 2 Spiders remain alive.**

So Forced Death Phase now works like this:
* AU(H/A)
* SRS
* Death Creation
* AU(Other)
* Death Phase
* AU(H/A)
* SRS
* AU(Other)                  //Not tested yet, but I guess there should be.
* Next step in the original Phase

Another problem is why Defile stops. I cannot find another reason but Defile doesn't kill Haunted **by itself**. But is it Hearthstone's _style_ to check that accurately?
