### ISSUE TITLE
Weapons that summon minions (Sword of Justice, Atiesh) with Leeching Poison heal your Hero when minions are summoned

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#788]
From #785

https://www.reddit.com/r/hearthstone/comments/6tirrb/bugs_introduced_with_the_90_patch/dlkyo8j/

> [[Sword of Justice]] combined with [[Leeching Poison]] seems to heal your hero for one HP each time you summon a minion. Seems like a strange interaction.

**Comment by ThePlayer14** [comment]
I think this is the same case with Atiesh.

**Comment by troggnostupidhs** [comment]
@ThePlayer14 Confirmed

Deck
AAEBAYO6AgTZAu0Fg6wCobcCDbQB+wGcArQCmwW5Bt0IxBaxsAKStgL4wQKBwgKpzQIA

![hearthstone screenshot 08-15-17 16 27 03](https://user-images.githubusercontent.com/22508641/29334818-b0751b8c-81d6-11e7-9229-dd86854aec96.png)

**Comment by ThePlayer14** [comment]
I think that Leeching Poison gives your weapon an enchantment that activates the Lifesteal effect when you hit "something" (thus your weapon loses 1 durability), and Sword of Justice and Atiesh are seemingly coded as when their trigger activates, the weapon attacks a phantom entity, which results in an activation trigger for the Lifesteal enchantment.
I'm interested in if the same scenario happens if your weapon is immune (by Runeforge Haunter's aura).

**Comment by troggnostupidhs** [comment]
Test it, you are correct. There's no heal when you weapon doesn't lose durability.

Deck
AAEBAYO6AgTZAu0Fg6wCobcCDbQB+wGcArQCmwW5Bt0IxBaStgL4wQKBwgKpzQLDzgIA

![hearthstone screenshot 08-15-17 19 58 02](https://user-images.githubusercontent.com/22508641/29341726-4dd4c248-81f4-11e7-9171-7e4a39f4abb8.png)

Also, if something is being hit, it is not a minion that takes damage. Frothing Berserker is not buffed.

![hearthstone screenshot 08-15-17 20 06 06](https://user-images.githubusercontent.com/22508641/29341908-70c29d60-81f5-11e7-986a-1712a01c523a.png)

**Comment by troggnostupidhs** [comment]
With weapon buffs. Suggested by @NightKev. Still only heals for 1.

Deck
AAEBAYO6AgTZAu0FxBahtwINtAH7AZwCtALLA5sFuQbdCJK2AvjBAoHCAqnNAsPOAgA=

(took this screenshot too late, it only healed for 1)
![hearthstone screenshot 08-15-17 20 43 03](https://user-images.githubusercontent.com/22508641/29342783-c9649af4-81fa-11e7-9bd9-a9b0eebf03a1.png)

![hearthstone screenshot 08-15-17 20 44 10](https://user-images.githubusercontent.com/22508641/29342784-cc30688a-81fa-11e7-905d-c8017f06766c.png)

**Comment by ThePlayer14** [comment]
So, it's the following I think:
The Leeching Poison enchantment is coded like something:

If the weapon loses durability, it attacked something (even if it's not used as a weapon), so for each durability loss, the Leeching Poison enchantment will heal the player for 1.
Runeforge Haunter's aura prevents it from happening since there was no durability loss, thus this strange interaction couldn't trigger.
I think its's only appearing for Triggered effect weapons.
I think they rushed some cards' testing phase, and did not tested any nooks and crannies for those bugs.

**Comment by NightKev** [comment]
Well, I can imagine they didn't think of putting Leeching Poison on Sword of Justice or Atiesh, for many reasons: difficult to get SoJ in Rogue (and harder still to get LP in Paladin); Rogue doesn't usually run Medivh; even if you manage to equip those weapons there's almost no reason to ever put LP on SoJ unless you're ultra desperate, and even then +1hp probably won't save you in most cases; putting it on Atiesh has slightly more merit just to summon a random 3-cost minion at least but it's still a rather bad play mostly.

In this case, I can understand them missing this weird interaction.

**Comment by ThePlayer14** [comment]
Well, that's why other games have PTR servers, so if you get a bug on the PTR, they'll fix it because they know what makes the bug, but in Hearthstone's case, introducing a PTR would cause some confusion for the casual players I think.

**Comment by boynedmaster** [comment]
@ThePlayer14 Does weapon attack + Runeforge Haunter not give you Lifesteal healing?

**Comment by Otto42** [comment]
@boynedmaster It does not give you healing when the weapon doesn't take damage. See the comment above from troggnostupidhs on August 15th where he tested that very thing.

**Comment by troggnostupidhs** [comment]
Possibly fixed

https://playhearthstone.com/en-us/blog/21098848

>Expending Sword of Justice’s durability as it is played will no longer grant +1 attack for the rest of the game.

**Comment by troggnostupidhs** [comment]
This is fixed.
