### ISSUE TITLE
Lich Kings' "Fallen Champions" inconsistent card text and buff text

### ISSUE THREAD

**Issue by judge2020** [HearthSim/hs-bugs#797]
As a paladin versus the Lich King, he plays the card "Fallen Champions"

![](https://judge2020.me/nfxKT.png)

but the buff text describes a different effect

![](https://judge2020.me/7PaSot.png)

"taking control" is different from resummoning the minion.

**Comment by troggnostupidhs** [comment]
Possibly falls under #881 since it is ambiguous text

**Comment by Jetz72** [comment]
I vote we just axe this one entirely. There aren't many ways the card text could be interpreted besides resummoning the minion under his control, since taking control of a dead minion would otherwise be meaningless. It's a complex mechanic summarized roughly, like Jaraxxus. Giving a loose description of a card's effects and revealing more specific details once it's in play is a pretty well established design pattern in Hearthstone, such as how Death's Shadow does through Shadow Reflection.

**Comment by troggnostupidhs** [comment]
I'm somewhat in support of closing this because I'd give more leeway for Adventure cards to be written   not as precisely. It's solo content and sometimes they want to add flavor to the encounter.

Let's see if we can get more feedback.

**Comment by Jetz72** [comment]
Nobody raised any objections here or in the Discord, so I think it's safe to close this for the reasons above.
