### ISSUE TITLE
Playing Shadow Word: Pain on Burly Rockjaw Trogg when Noggenfogger is on board will cause a disconnect and remove both minions

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#839]
https://youtu.be/xxmD2r3FSCM?t=497

**Comment by ThePlayer14** [comment]
I think it's because Rockjaw Trogg is a 3-Attack minion, it's initially a legal target for Shadow Word: Pain but after casting the spell on it, the Trogg gets buffed to 5 attack via its effect and there are no legal targets for Noggenfogger to select a target because Noggenfogger and the Trogg have 5 Attack while the spell needs a 3-attack minion, so the game fixes this logical problem by deleting both minions.

**Comment by troggnostupidhs** [comment]
Is this a duplicate of #697 ?
