### ISSUE TITLE
Unidentified Elixir without Bonus effect enchantment uses wrong artwork

### ISSUE THREAD

**Issue by PattuX** [HearthSim/hs-bugs#873]
https://youtu.be/IEBoD3FXS6o?t=1m29s

In this case played by Grand Archivist therefore without any bonus effect. Not sure if it's reproducible (and whether it always uses Blessing of Wisdom's artwork) and whether it's correct for upgraded elixirs. 

edit: somtimes it uses the "Missing Ability Art" thing https://www.reddit.com/r/hearthstone/comments/7ktco9/tastes_like/

**Comment by troggnostupidhs** [comment]
Deck
AAEBAZ/HAgKxsALQ5wIO8gH7AZwCtALcAuAEoQa5BvIMkA/6sALwuwLkzAK/5QIA

Starts out as something random
![img000](https://user-images.githubusercontent.com/22508641/34236490-cdd28c34-e5c5-11e7-92d7-cafee8dc6b9e.png)

![img002](https://user-images.githubusercontent.com/22508641/34236500-daf0667a-e5c5-11e7-82d1-8ecd48034dba.png)

But can sometimes be fixed by playing cards, possibly another Elixir
![img001](https://user-images.githubusercontent.com/22508641/34236527-f8142fc0-e5c5-11e7-9700-fb6360212a5a.png)

![img004](https://user-images.githubusercontent.com/22508641/34236532-fd025052-e5c5-11e7-9d9f-0ddb5400cc18.png)

**Comment by troggnostupidhs** [comment]
Fixed

![img000](https://user-images.githubusercontent.com/22508641/44314445-382c4b80-a3e7-11e8-801e-35c83eb01917.png)
