### ISSUE TITLE
Monster Hunt: Sometimes a boss will appear in the wrong round

### ISSUE THREAD

**Issue by troggnostupidhs** [HearthSim/hs-bugs#941]
~~~Possibly occurs with draws.~~~

https://us.battle.net/forums/en/hearthstone/topic/20762906105

> so during a monster hunt in the 7/8 encounter i had a draw ( i killed the boss but the spell triggered another time where it also killed me) the ending screen told me "defeat" but i still was at 7/8 so i had to beat the boss no. 7 again. I did that and then, at the final boss i got Gobbles as opponent who only had like 7 cards in his deck, but still had 70 health.
> it was not a real challenge to beat him :)

> Thanks for the reports. Looking into it. :)

**Comment by PattuX** [comment]
Also happens when you win your 7th match as a Death Knight from another class. If the DK happens to be Warrior/Mage/Rogue/Hunter you'll get the corrosponding nemesis fight, for any of the other five you'll get another boss which seems to be Gobbles in many cases. Some also still report that it happens randomly as Darius although Blizzard said they hotfixed that issue: https://us.battle.net/forums/en/hearthstone/topic/20761086790#post-19

Not that easy to figure out what exactly causes it as most people don't have evidence of what happened in the 7th fight.

**Comment by troggnostupidhs** [comment]
More reports

https://www.reddit.com/r/hearthstone/comments/8g2tik/bug_i_fought_the_forlorn_lovers_as_my_8th_boss/

https://www.reddit.com/r/hearthstone/comments/8g0jid/defeated_gobbles_as_my_final_boss_on_toki_due_to/

https://www.reddit.com/r/hearthstone/comments/8fygsl/gobbles_as_final_boss/

https://www.reddit.com/r/hearthstone/comments/8fxrxk/gobbles_as_the_8th_boss_witchwood_dungeon/

**Comment by troggnostupidhs** [comment]
Closing this. Can reopen if there are more reports.
