### ISSUE TITLE
Copies of Echo cards from Lorewalker Cho remain in hand at the end of turn (not consistent with Unstable Evolution)

### ISSUE THREAD

**Issue by ruthnaebeck** [HearthSim/hs-bugs#950]
If you play Echo copies of Unstable Evolution with Lorewalker Cho in play, your opponent receives an Echo copy which disappears.

Evidence:
https://clips.twitch.tv/OnerousResolutePicklesBigBrother

*This could be intended behavior.

**Comment by troggnostupidhs** [comment]
I agree with what he says at the end. If the first one stays, then it seems ok. I can test it later.

**Comment by Jetz72** [comment]
Cho doesn't make ghostly copies of actual Echo cards when they're repeatedly played, though. In that regard, it is a bit inconsistent. 

However, Peter Whalen brought up the subtle differences between how Unstable Evolution and Echo work prior to release: https://www.youtube.com/watch?v=dERH5ZQq5vk&t=38m20s 

I suspect it's more a matter of "if it ain't broke don't fix it" than a deliberate design choice, so I'm not sure I'd bank on this unchanged the same if the mechanic is ever revisited. But either way, it would appear that the inconsistency is at least sorta intended. I just figured I'd document these details here for future reference.

**Comment by troggnostupidhs** [comment]
@Jetz72 Thanks for pointing that out. I didn't know they behaved differently. In my opinion, the Echo cards should behave like Unstable Evolution. I'll leave this open as 'may be intended' for the reasons you mentioned.

**Comment by Jetz72** [comment]
Well as far as I can tell, the underlying reason for the difference is that Unstable Evolution (LOOT_504) creates a token spell (LOOT_504t), which has the "remove at end of turn" effect built in to it. Echo cards create duplicates of themselves with the "Ghostly" tag set. Cho is able to make ghostly copies of the former and not the latter because he creates new copies of the base card. In the case of Unstable Evolution, that means more copies of "LOOT_504t", which have the disappearing part built in.

Not sure which side I personally fall on, whether Echo should work more like Unstable Evolution or vice versa, but I guess that's not really up to any of us.

**Comment by ruthnaebeck** [comment]
From 11.4 patch notes:
https://news.blizzard.com/en-us/hearthstone/21943493/hearthstone-update-11-4-july-10-the-boomsday-project-pre-purchase

> Resolved an issue with Lorewalker Cho’s interaction with Unstable Evolution and cards with Echo.

**Comment by ceceita** [comment]
ok i tested and all the copies stay in enemy hand , and back in my hand when used by enemy , the only strange thing is that one of them have the purple gem , and the other have no gem , the one whit purple gem is the real card.

enemy 2 cards , i play cho
![](https://i.imgur.com/WUZnWro.jpg)
i evolve 3 times ,  enemy has now 5 cards
![](https://i.imgur.com/K34Yv6F.jpg)
he played 2 evolve and 1 minion , here AI is stupid becouse dont use the echo version , btw i got back the 2 spells
![](https://i.imgur.com/7TzqHEu.jpg)
