### ISSUE TITLE
Shifter Zerus keeps buffs

### ISSUE THREAD

**Issue by CCTrainXD** [HearthSim/hs-bugs#999]
## Bug report
When Shifter Zerus' transforms into a card that swaps stats at the end of turn, it retains those swapped stats when played for another minion.
### Expected Behavior
Stats are erased, and the transformation effect overrides and the new minion should have its own stats. Not sure how that works.

### Actual Behavior
Stats remain the same throughout transformations. If zerus transformed into a 3/8 gilnean royal guard, it turns into an 8/3 Gilnean Royal Guard(Worgen form) and all future transformations retain this 8/3 statline. 

### Steps to reproduce behavior
Wait for shifter zerus to transform into a card that swaps attack/health at the end of turn. End turn. At the start of your turn, note stats of the transformed zerus.
### Log/Screenshots
Minion affected by the 2 mana neutral 1/4 Spell dmg +1  swapper. In hand.
![hearthstone screenshot 07-11-18 17 45 23](https://user-images.githubusercontent.com/28812825/42601473-b5cdd914-8533-11e8-963f-6642c800770c.png)
On the board after playing it.
![hearthstone screenshot 07-11-18 17 45 39](https://user-images.githubusercontent.com/28812825/42601475-b5dfc9ee-8533-11e8-9a27-3713bbf351be.png)

Minion affected by the 3 mana hunter card with 2/5 stealth swapper. In hand.
![hearthstone screenshot 07-11-18 17 54 37](https://user-images.githubusercontent.com/28812825/42601505-d39cddaa-8533-11e8-8688-b00c96a877c8.png)

When played on the board.
![hearthstone screenshot 07-11-18 17 54 52](https://user-images.githubusercontent.com/28812825/42601506-d3aaa4d0-8533-11e8-8325-0d04a19ba8fa.png)

**Comment by 10925** [comment]
Personally I don't think this is a bug.
attack/health swapping cards works like a buff, and zerus would remain all the buff like cost reduce from Thaurission, or when it transform to old Bolvar, the attack buff would remain too.

**Comment by CCTrainXD** [comment]
Attack/health swapping cards do not count as buffs. When you play the card, it has no buffs listed on it so it cannot be classified as a buff.

**Comment by 10925** [comment]
Yeah, you can argue that it didn't shows that, but that's how does it really work, it's at end of the turn, give a"buff" to set new attack and health to the transform version.

**Comment by Jetz72** [comment]
In the April 16th hotfix, an identical behavior was supposedly "fixed" for Chameleos.

>Fixed an issue where Chameleos retained the stats after copying a transforming Worgen card that would make all future cards copied maintain those stats(including Hero Cards and Weapons)

It's clear now that the fix was only specific to Chameleos, and does not extend to other shifters. However, it was described as an issue, rather than an undocumented side effect like #930. It is safe to assume that this is, while mechanically logical, unintended.

**Comment by PattuX** [comment]
This has been the case for a long time and never caused any trouble until Chameleos came around (and also Kingsbane + Liam) as it was able to transform between different types of card. I want to say in an optimal universe minion and weapon buffs would be distinguished and couldn't be applied to weapons/minions and hero cards but I don't think that will happen.

Anyway, this specific bug is happening because, like crazed Alchemist, swapping stats as an enchantment is not actually swapping the stats but is an enchantment that sets Attack and Health to some set values, thus overwriting any previous buffs, even if they are temporary (Abusive Seageant + Crazed Alchemist) or even if they were granted by auras (taken into account for swapping, then re-applied after swapping, see Stormwind Champion + Crazed Alchemist).

This is inconsistent with Chameleos (if the patch notes are correct) and probably also inconsistent with how other buffs (say +1/+1) are handled (assuming this because all reports include swapping effects specifically).

**Comment by troggnostupidhs** [comment]
#925 and #930 are related to this

**Comment by troggnostupidhs** [comment]
https://www.reddit.com/r/hearthstone/comments/8yj9jf/playing_lady_in_white_in_the_tavern_brawl_makes/

**Comment by Jetz72** [comment]
Suggesting that Zerus' ability to keep any buffs at all is a bug, conflicts with issue #930, where it is suggested that it's a bug for Chameleos to lose these buffs.

Perhaps it'd be better to consolidate the matter of the inconsistency in 930. This issue could instead be used for the contribution by the Worgen cards to this undesirable consequence. In other words, if Zerus is actually meant to retain normal mana, attack, and health modifiers, it might still be considered a bug that Worgen cards pass their "swapped" stats on, or that in-hand effects can activate for cards that a shifter has taken the form of.

After all, Zerus retaining buffs was widely considered a deliberate feature before Witchwood, and it seems unwise to interpret the simple rapid hotfix to Chameleos as any indication of how all these cards are meant to work together.

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/21965466/

> Shifter Zerus, Molten Blade, and Shifting Scroll all transform in your hand at the start of every turn. Following the 12.0 update, they will no longer keep any enchantments when they transform. This includes things like hand buffs and Emperor Thaurissan mana-cost discounts.

**Comment by 10925** [comment]
So it's a Mechanics update rather than a bug fix.
Though the old mechanic is inconsistent. Tess is inconsistent too, we cannot say inconsistent must be a bug.

**Comment by troggnostupidhs** [comment]
I would say this about it. It is unintended behavior. While not a pure 'bug', I don't think it will hurt to track it until it is fixed.

With Tess, they had said the original behavior was intentional. They changed it to be consistent, and then changed it back. I think the difference here is that they are saying the inconsistency is not intended / desired.

**Comment by 10925** [comment]
I think we can find q&a that said Zerus would keep buff from Mistcaller.
https://twitter.com/PlayHearthstone/status/722183083907100674
So I do think Zerus keep buff is intended, or was intended.

Chameleos can keep buff when it first published, it has to be inconsistency with other changeing cards. Since it causes bug, and it can change it's own card type.
While other card like shifter zerus would keep it's own type. So they needn't to be consistency with chameleos.

And I don't think I see they said about this mechanic update is about consistency. Which sentence meaning "inconsistency is not intended / desired"?

**Comment by troggnostupidhs** [comment]
https://playhearthstone.com/en-us/blog/21964710

> When Shifter Zerus transforms into a Worgen card, the next card it transforms into will no longer keep those stats.
